export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNSUPPORTED_PARAMETER: 'UNSUPPORTED_PARAMETER',
  INVALID_CATEGORY: 'INVALID_CATEGORY',
  NOT_FOUND: 'NOT_FOUND',
  PAGE_NOT_FOUND: 'PAGE_NOT_FOUND',
  COMPONENT_NOT_FOUND: 'COMPONENT_NOT_FOUND',
  FORBIDDEN_ORIGIN: 'FORBIDDEN_ORIGIN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
